services:
  backend:
    container_name: oyster-backend-service
    image: oyster-backend-service
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mqtt
      - mongo
  mongo:
    container_name: oyster-mongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: always
  mqtt:
    container_name: oyster-message-broker
    image: oyster-message-broker
    build: ./broker
    ports:
      - "1883:1883"
  frontend:
    container_name: oyster-frontend
    image: oyster-frontend
    build: ./oyster-frontend
    ports:
      -  "5173:5173"
    links:
      - backend
    volumes:
      - ./oyster-frontend:/usr/src/app
      - /usr/src/app/node_modules
  bridge:
    container_name: oyster-bridge
    image: oyster-bridge
    build: ./oyster-bridge
    profiles: ["bridge"]
    links:
      - mqtt
    volumes:
      - ./oyster-bridge/data:/python-docker/data
    devices:
      - "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_2e74289bdc24ec119aa676c2a8a1c857-if00-port0:/dev/serial0"
